@startuml
title Verletzung der Dependency Rule (ExportWorkoutHistoryServiceBad)

' ======= Schichtendarstellung =======
    class core.usecase.workout.export.ExportWorkoutHistoryService{
    - repo : InMemoryWorkoutRepository
    + ExportWorkoutHistory(InMemoryWorkoutRepository)
    + export(String, Path)

}

 package "adapters.persistence.inmemory" {
     class InMemoryWorkoutRepository {
         - workouts: List
         - idCounter: AtomicInteger
         + saveWorkout(workout)
         + findAll()
         + findById(id)
         + findByUser(username)
         + deleteById(id)
     }
 }

/' === Regelwidrige Abhängigkeit === '/
ExportWorkoutHistoryService--> InMemoryWorkoutRepository

note right of ExportWorkoutHistoryService
  Use-Case (innen) kennt den
  konkreten InMemory-Adapter (außen).
  Abhängigkeit zeigt nach außen –
  Dependency Rule verletzt.
end note
@enduml