@startuml

class SmarterWorkoutGenerator {
	{field} -exerciseRepository : IExerciseRepository
	{field} -random : java.util.Random
	{method} -filterAndSelectExercises ( exercises : List , count : int , ExerciseCategory...3 : ExerciseCategory; ) : List
	{method} +generateWorkout ( paramString1 : String , paramWorkoutType2 : WorkoutType , paramTrainingSplit3 : TrainingSplit , paramint4 : int , paramString5 : String ) : List
	{method} -getFullBodyWorkout ( paramList1 : List ) : List
	{method} -getPushPullLegWorkout ( paramList1 : List , paramint2 : int ) : List
	{method} -getRandomExercises ( paramList1 : List , paramint2 : int ) : List
	{method} -getUpperLowerWorkout ( paramList1 : List , paramint2 : int ) : List
	{method} -selectExercisesForDay ( paramList1 : List , paramTrainingSplit2 : TrainingSplit , paramint3 : int ) : List
}






@enduml