@startuml User_Entity
title Domain Entity – User

package "core.domain.user" {
  class User {
    - id : int
    - username : String
    - password : Password
    - gewicht : double
    - groese : double
    - geburtstag: Birthday
  }
}

note right of User
  User ist eine Entity, da sie durch eine eindeutige ID
  identifiziert
end note

@enduml
